# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-28 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200128_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
    ]
